apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
  compileSdkVersion project.hasProperty('compileSdkVersion') ? project.compileSdkVersion : 34

  defaultConfig {
    minSdkVersion project.hasProperty('minSdkVersion') ? project.minSdkVersion : 23
    targetSdkVersion project.hasProperty('targetSdkVersion') ? project.targetSdkVersion : 34
    versionCode 1
    versionName "1.0"
  }

  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlinVersion"
}
